import { colors, spacing, borderRadius } from '../styles/theme';

export const getAdminStyles = () => {
  return {
    container: {
      padding: spacing.xl,
      maxWidth: '1400px',
      margin: '0 auto',
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 25%, #f093fb 50%, #4facfe 75%, #00f2fe 100%)',
      minHeight: '100vh',
      position: 'relative',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: spacing.xl,
      background: `linear-gradient(135deg, ${colors.primary.main} 0%, ${colors.primary.dark} 100%)`,
      padding: spacing.lg,
      borderRadius: borderRadius.medium,
      color: colors.white,
      boxShadow: '0 4px 12px rgba(66, 133, 244, 0.3)',
    },
    title: {
      fontSize: '32px',
      fontWeight: 'bold',
      margin: 0,
      color: colors.white,
    },
    tabs: {
      display: 'flex',
      borderBottom: `2px solid ${colors.primary.main}`,
      marginBottom: spacing.lg,
      gap: 0,
      backgroundColor: colors.white,
      borderRadius: `${borderRadius.medium} ${borderRadius.medium} 0 0`,
      boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
      overflow: 'hidden',
    },
    tab: {
      background: 'none',
      border: 'none',
      padding: `${spacing.md} ${spacing.lg}`,
      fontSize: '14px',
      cursor: 'pointer',
      fontWeight: '600',
      transition: 'all 0.3s ease',
      color: colors.text.secondary,
      borderBottom: '3px solid transparent',
      marginBottom: '-2px',
    },
    statsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
      gap: spacing.lg,
      marginBottom: spacing.xl,
    },
    statCard: {
      padding: spacing.lg,
      textAlign: 'center',
      background: colors.white,
      borderRadius: borderRadius.medium,
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
      border: `1px solid ${colors.gray[200]}`,
      transition: 'all 0.3s ease',
      cursor: 'pointer',
    },
    statLabel: {
      color: colors.text.secondary,
      fontSize: '12px',
      marginBottom: spacing.sm,
      textTransform: 'uppercase',
      letterSpacing: '0.5px',
      fontWeight: '700',
    },
    statValue: {
      fontSize: '36px',
      fontWeight: '700',
      color: colors.primary.main,
      lineHeight: '1.2',
    },
    tableCard: {
      padding: spacing.lg,
      background: colors.white,
      borderRadius: borderRadius.medium,
      boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
      border: `1px solid ${colors.gray[200]}`,
      marginBottom: spacing.xl,
    },
    tableTitle: {
      fontSize: '24px',
      fontWeight: '700',
      marginBottom: spacing.lg,
      marginTop: 0,
      color: colors.gray[900],
      paddingBottom: spacing.md,
      borderBottom: `2px solid ${colors.gray[100]}`,
    },
    tableContainer: {
      overflowX: 'auto',
      borderRadius: borderRadius.small,
    },
    table: {
      width: '100%',
      borderCollapse: 'collapse',
      fontSize: '14px',
    },
    tableHeader: {
      backgroundColor: colors.gray[50],
      borderBottom: `2px solid ${colors.gray[200]}`,
    },
    tableCell: {
      padding: spacing.md,
      textAlign: 'left',
      borderBottom: `1px solid ${colors.gray[200]}`,
      color: colors.text.primary,
      fontWeight: '500',
    },
    tableRow: {
      borderBottom: `1px solid ${colors.gray[200]}`,
      transition: 'background-color 0.2s ease',
    },
    badge: {
      padding: '6px 12px',
      borderRadius: borderRadius.small,
      fontSize: '11px',
      fontWeight: '700',
      display: 'inline-block',
      textTransform: 'uppercase',
      letterSpacing: '0.3px',
    },
    actionButtons: {
      display: 'flex',
      gap: spacing.sm,
      alignItems: 'center',
    },
    actionBtn: {
      width: '36px',
      height: '36px',
      border: 'none',
      borderRadius: borderRadius.small,
      cursor: 'pointer',
      fontWeight: 'bold',
      fontSize: '16px',
      transition: 'all 0.2s ease',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    loadingContainer: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      minHeight: '100vh',
      backgroundColor: colors.background.default,
    },
    loadingSpinner: {
      width: '50px',
      height: '50px',
      border: `4px solid ${colors.gray[200]}`,
      borderTop: `4px solid ${colors.primary.main}`,
      borderRadius: '50%',
      animation: 'spin 1s linear infinite',
    },
  };
};
